#!/bin/sh
#
#PBS -A NFI006
#PBS -N RSD
#PBS -j oe
#PBS -m abe
#PBS -M rahul.sampath@gmail.com
#PBS -l walltime=0:05:00,nodes=2:ppn=16
#PBS -q batch
#

cd ${PBS_O_WORKDIR}/bin

date

export MyN=33
export MyP=32
export MyG=4

export OMP_NUM_THREADS=1
export MPI_GROUP_MAX=32000
export MPI_COMM_MAX=32000

mpiexec_mpt -np ${MyP} ./testrsd 0 -N ${MyN} -inner_ksp_max_it ${MyG} | tee rsdN${MyN}P${MyP}G${MyG}.txt


